### PR TITLE
Created a CDK Construct to deploy Komiser helm chart on EKS cluster.

### PR DESCRIPTION
**Pull request by sshiv5768**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 🔌 Chore (Release)
- [ ] ⏩ Revert

## Description
 Created AWS CDK app that contains komiser construct which helps to deploy the helm chart to AWS EKS cluster.
 

## Related Issues
Refer the issue https://github.com/tailwarden/komiser/issues/897 for more details.

## Mobile & Desktop Screenshots/Recordings
Need help, while running ``cdk deploy`` it always gives the below error. Although I am using a EKS supported ``KubernetesVersion`` by considering the official [documentation](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html).
```
Received response status [FAILED] from custom resource. Message returned: unsupported Kubernetes version 
```
Screenshot 2023-10-02 at 4 50 16 PM

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📓 docs.komiser.io
- [ ] 📕 storybook
- [ ] 🗒 Code comment intelliSense
- [ ] 🙅 no documentation needed

## Complete the checklist before considering this PR as "Ready to review"

- [x] Pull the Code - Ensure the functionality works locally.
- [ ] Compare to the Design - Check if everything matches the design specifications. Validate the consistency of colors, fonts, paddings, etc.
- [ ] Responsive Testing - Resize the browser window to ensure nothing breaks on mobile
- [ ] Code Quality - Ensure best coding practices are used \*
- [ ] Ensure no commented-out code or debug logs are left behind.
- [ ] Check for code modularity and reusability.
- [ ] Check for descriptive variable names: e.g., "totalPrice" not "tp".
- [ ] Ensure there are no linting errors `npm run lint`
- [ ] Ensure the code passes the build `npm run build`
- [ ] Ensure there are no inline error disabling/ignores
- [ ] Ensure all newly added dependencies are actually necessary (package.json)
- [ ] Check that the PR has a title and description

### CODE REVIEW

**Comment by sshiv5768** [comment]
@mlabouardy need help with this PR.

**Comment by AvineshTripathi** [comment]
Hey @sshiv5768 Thanks a million for working on this, can we not use python for this and shift to either golang or typescript cause those are the languages we have been using in komiser. 

If you need help with this we can connect and change this to your prefered language. Let me know your thoughts

**Comment by Azanul** [comment]
> @mlabouardy need help with this PR.

I've got this to work. Could you give me permission to push to your branch

**Comment by Azanul** [comment]
https://github.com/tailwarden/helm/pull/19

**Pull request closed without merging**
